apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  labels:
    app: kn-kapturer-be
    env: dev
  name: kn-kapturer-be
  namespace: NAMESPACE
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - env:
          - name: ENTRYPOINT
            value: ./dist/index.js
          envFrom:
          - configMapRef:
              name: kabe-conf-dev-xxx
          - secretRef:
              name: kabe-secret-dev-xxx
          name: kn-kapturer-be
          image: eu.gcr.io/REGISTRY/kn-kapturer-backend:v1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          resources:
            requests:
              memory: 500Mi
              cpu: 800m
            limits:
              memory: 1000Mi
              cpu: 1500m
          livenessProbe:
            httpGet:
              path: /v1
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 60
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /v1
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 60
            failureThreshold: 5
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  labels:
    app: kn-kapturer-clk
    env: dev
  name: kn-kapturer-clk
  namespace: NAMESPACE
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - env:
          - name: ENTRYPOINT
            value: ./dist/index-clk.js
          envFrom:
          - configMapRef:
              name: kabe-conf-dev-xxx
          - secretRef:
              name: kabe-secret-dev-xxx
          name: kn-kapturer-clk
          image: eu.gcr.io/REGISTRY/kn-kapturer-backend:v1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          resources:
            requests:
              memory: 64Mi
              cpu: 50m
            limits:
              memory: 128Mi
              cpu: 100m