apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  labels:
    app: kn-krawler
    env: dev
  name: kn-krawler
  namespace: NAMESPACE
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/target-utilization-percentage: "100"
        autoscaling.knative.dev/class: kpa.autoscaling.knative.dev
        autoscaling.knative.dev/metric: concurrency
        autoscaling.knative.dev/min-scale: "0"
        autoscaling.knative.dev/max-scale: "100"
    spec:
      containerConcurrency: 1
      containers:
        - name: kn-krawler
          image: eu.gcr.io/REGISTRY/kn-krawler:v1.0.1
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: kabe-conf-dev-xxx
            - secretRef:
                name: kabe-secret-dev-xxx
          env:
            - name: FUNC_LOG_LEVEL
              value: "info"
            - name: CHROMIUM_PATH
              value: "/usr/bin/chromium-browser"
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          resources:
            requests:
              memory: 1000Mi
              cpu: 500m
            limits:
              memory: 1280Mi
              cpu: 750m